// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Email struct {
	ID        int64
	Subject   sql.NullString
	Createdat sql.NullInt64
	Expiresat sql.NullTime
}

type Emailaddress struct {
	ID      int64
	Type    sql.NullString
	Address sql.NullString
	Emailid sql.NullInt64
}

type Inbox struct {
	ID          string
	Address     sql.NullString
	Textcontent sql.NullString
	Htmlcontent sql.NullString
	Createdat   sql.NullInt64
	Emailid     sql.NullInt64
}
